# Usar una imagen base oficial

FROM alpine:latest



# Etiqueta para identificar el mantenedor (opcional)

LABEL maintainer="ericconcejero"



# Imprimir un mensaje cuando se ejecute el contenedor.

CMD echo "¡Hola, esta es la pirmera imagen de docker de radiantarena!"
